version: '3'
services:
  orchid-vms:
    container_name: orchid-vms
    build:
      context: .
    ports:
      - '8080:8080'
      - '5554:5554'
    volumes:
      - './orchives:/orchives'
      - './orchid_server:/var/lib/orchid_server'
      - './etc/opt:/etc/opt'